build.gradle, src/main/java/plus/maa/backend/config/OpenFeignConfig.java, src/main/java/plus/maa/backend/repository/GithubRepository.java, src/main/java/plus/maa/backend/repository/entity/ArknightsTilePos.java, src/main/java/plus/maa/backend/repository/entity/GithubContent.java, src/main/java/plus/maa/backend/service/GithubService.java, src/main/resources/application-template.yml
定时任务同步到mongodb的还没写，需要先讨论同步频率之类的，定时任务框架我也没用过，来个大佬帮忙做或者指点下我来做。
=> feat: 接入 GitHub api，接入 MAA 地图数据

src/main/java/plus/maa/backend/handler/GlobalExceptionHandler.java
避免抛出 MaaResultException 时直接进入 defaultExceptionHandler 吞掉报错信息
=> [ADD] 新增 MaaResultException 的统一异常处理

build.gradle, src/main/java/plus/maa/backend/common/utils/converter/ArkLevelConverter.java, src/main/java/plus/maa/backend/common/utils/converter/MaaUserConverter.java, src/main/java/plus/maa/backend/controller/response/ArkLevelInfo.java, src/main/java/plus/maa/backend/controller/response/MaaUserInfo.java, src/main/java/plus/maa/backend/service/ArkLevelService.java, src/main/java/plus/maa/backend/service/UserService.java
@Anselyuki  修改了用户相关代码
@john180  修改了 level 相关代码
=> feat: 引入 MapStruct，提升性能，增强转换工具扩展性

src/main/java/plus/maa/backend/common/utils/JsonUtils.java, src/main/java/plus/maa/backend/handler/AuthenticationEntryPointImpl.java
[ADD] JsonUtils, 创建缺省的 objectMapper bean, 默认蛇形命名
[FIX] AuthenticationEntryPointImpl 类新建 ObjectMapper 实现实体类转 json 默认驼峰命名的 bug
=> 新增 Json 工具类，修复一处不正确的驼峰命名

src/main/java/plus/maa/backend/repository/entity/ArkLevel.java, src/main/java/plus/maa/backend/repository/entity/gamedata/ArkCharacter.java, src/main/java/plus/maa/backend/repository/entity/gamedata/ArkTower.java, src/main/java/plus/maa/backend/service/ArkGameDataService.java, src/main/java/plus/maa/backend/service/ArkLevelParserService.java
完成剿灭、悖论模拟、危机合约、保全Level数据转换
Level数据增加stageId字段
=> 完成剿灭、悖论模拟、危机合约、保全Level数据转换

build.gradle, src/main/java/plus/maa/backend/config/external/CopilotBackup.java, src/main/java/plus/maa/backend/config/external/MaaCopilotProperties.java, src/main/java/plus/maa/backend/repository/CopilotRepository.java, src/main/java/plus/maa/backend/service/CopilotService.java, src/main/java/plus/maa/backend/task/CopilotBackupTask.java, src/main/resources/application-template.yml
实现 [71](https://github.com/MaaAssistantArknights/MaaBackendCenter/issues/71)
=> 作业自动备份到GitHub--需要服务端配置 ssh 才能使用

src/main/java/plus/maa/backend/config/security/SecurityConfig.java, src/main/java/plus/maa/backend/controller/FileController.java, src/main/java/plus/maa/backend/handler/GlobalExceptionHandler.java, src/main/resources/application.yml
@dragove @Handiwork   佬 这是通过GridFS进行存储 通过指定日期 返回批量图片压缩包  目前是简单的样例
=> feat: 文件上传/批量下载

.github/workflows/openapi.yml, build.gradle, client-config/ts-fetch.json
Add openapi workflow, generating openapi docs and clients for cpp/csharp/rust/ts
=> Chore: openapi workflow

src/main/java/plus/maa/backend/controller/response/copilot/ArkLevelInfo.java, src/main/java/plus/maa/backend/repository/entity/ArkLevel.java, src/main/java/plus/maa/backend/service/ArkLevelService.java, src/main/java/plus/maa/backend/service/CopilotService.java, src/main/java/plus/maa/backend/task/CopilotBackupTask.java, src/main/java/plus/maa/backend/task/CopilotScoreRefreshTask.java, src/main/resources/application.yml
避免特殊情况下，作业作者使用以前关闭的地图，导致热度被莫名扣减
=> 地图信息新增服务器认为的关闭时间。作业热度惩罚仅限首次上传时间于地图关闭前。

.github/workflows/openapi.yml, client-config/ts-fetch.json
不确定能不能用，先试试（
流程是这样：
1. 把 https://github.com/MaaAssistantArknights/maa-copilot-client-ts 拉到 maa-copilot-client-ts 目录
2. 把生成好的 client 覆盖到 maa-copilot-client-ts
3. 提交 PR 到对面 repo
4. 给第 3 步生成的 commit 打上 version tag
=> ci: submit ts client to maa-copilot-client-ts

.github/workflows/openapi.yml
=> ci: directly push changes to maa-copilot-client-ts

src/main/kotlin/plus/maa/backend/service/CommentsAreaService.kt, src/main/kotlin/plus/maa/backend/service/EmailService.kt, src/main/resources/static/templates/ftlh/mail-comment-notification.ftlh
=> chore: pangu

src/main/kotlin/plus/maa/backend/config/external/SensitiveWord.kt, src/main/kotlin/plus/maa/backend/service/CommentsAreaService.kt, src/main/kotlin/plus/maa/backend/service/sensitiveword/SensitiveWordService.kt, src/main/resources/sensitive-word-whitelist.txt, src/test/kotlin/plus/maa/backend/service/sensitiveword/SensitiveWordServiceTest.kt
Close https://github.com/MaaAssistantArknights/maa-copilot-frontend/issues/378
=> feat: 文字内容敏感词增加白名单功能

src/main/kotlin/plus/maa/backend/service/CopilotService.kt
https://github.com/MaaAssistantArknights/maa-copilot-frontend/issues/381
=> Fix: 排除干员和指定干员错误的使用正则

src/main/kotlin/plus/maa/backend/service/CopilotService.kt
=> fix: adjust the word segmentation query logic

src/main/kotlin/plus/maa/backend/repository/UserRepository.kt, src/main/kotlin/plus/maa/backend/repository/entity/MaaUser.kt, src/main/kotlin/plus/maa/backend/service/UserService.kt
防止创建相同用户名用户、防止用户改名为已有用户名
去除前后空白字符需要先修改前端，不然修改用户名会出现前后端不一致的问题
=> feat: 添加用户名重复校验

src/main/kotlin/plus/maa/backend/service/segment/SegmentService.kt, src/test/kotlin/plus/maa/backend/service/segment/SegmentServiceTest.kt
=> refactor: 更新segment逻辑（需要重建整个maa_copilot表的segment）

src/main/kotlin/plus/maa/backend/config/external/SegmentInfo.kt, src/main/kotlin/plus/maa/backend/service/CopilotService.kt, src/main/kotlin/plus/maa/backend/service/segment/SegmentService.kt
=> feat: use memory inverted index

src/main/kotlin/plus/maa/backend/cache/InternalComposeCache.kt, src/main/kotlin/plus/maa/backend/cache/transfer/CopilotInnerCacheInfo.kt, src/main/kotlin/plus/maa/backend/service/CopilotService.kt
错误的拷贝了Counter，导致作业详情页和作业列表的浏览量数据不一致
=> fix: cache error view counter

src/main/kotlin/plus/maa/backend/cache/InternalComposeCache.kt, src/main/kotlin/plus/maa/backend/config/security/SecurityConfig.kt, src/main/kotlin/plus/maa/backend/controller/SystemController.kt
提供缓存命中情况的接口 & 把不稳定的soft ref缓存改为固定的过期时间
=> feat: add intra process cache stat & change cache evict time
